version: '2'
services:
  sfserver:
    image: vinanrra/satisfactory-server
    container_name: sfserver
    environment:
      - START_MODE=1 #Change between START MODES
      - PUID=1000 # Remember to use same as your user
      - PGID=1000 # Remember to use same as your user
      - TimeZone=Europe/Madrid
      - TEST_ALERT=NO
      - BACKUP=YES # Backup server at 5 AM
      - MONITOR=YES # Keeps server up if crash
    volumes:
      - ./ServerFiles:/home/sfserver/serverfiles/ #Optional, serverfiles
      - ./log:/home/sfserver/log/ #Optional, logs
      - ./backups:/home/sfserver/lgsm/backup/ #Optional, backups
      - ./LGSM-Config:/home/sfserver/lgsm/config-lgsm/sfserver # Optional, LGSM-Config
    ports:
      - 15777:15777/udp
      - 15000:15000/udp
      - 7777:7777/udp
    restart: unless-stopped #NEVER USE WITH START_MODE=4 or START_MODE=0
